### ISSUE TITLE
Change config to environmental variables

### ISSUE THREAD

**Issue by tkadlec** [WebPageTest/webpagetest-slack#7]
We currently drop the API key and Slack token in a JSON config file, but that means we are making it a lot easier for folks to accidentally expose credentials in their repo.

Since most platforms will have a way to provide secure environmental variables anyway, we should ditch the config file and use environmental variables for these instead.

**Comment by Siddhantshukla814** [comment]
https://github.com/WebPageTest/webpagetest-slack/pull/9
